version: "3"

volumes:
  db-data:

services:
  db:
    platform: linux/amd64
    image: mysql:8.0
    # restart: always
    ports:
      - "4406:3306"
    user: 1000:1000
    environment:
      MYSQL_DATABASE: coeteco_reserve_development
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - coeteco_reserve_network
    # command: --bind-address=0.0.0.0
    command: mysqld --innodb_use_native_aio=0