name: Node.js 18 Build and Test on Pull Request

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - '.storybook/**'
      - 'package.json'
      - 'yarn.lock'
      - 'tsconfig.json'
      - 'jest.config.js'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
