name: JavaScript CI with Bun
on:
    workflow_dispatch:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop
        paths:
            - 'src/**/*'
            - '.github/workflows/**/*'
            - '.storybook/**/*'
            - 'bun.lockb'
            - 'tsconfig.json'
            - 'jest.config.js'
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    setup:
        name: JavaScript Setup
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                bun-version: [1.0.1]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v3
            - name: Use Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: ${{ matrix.bun-version }}
            - name: Cache Restore devDependencies
              id: cache-restore-dev-depends
              uses: actions/cache/restore@v3
              with:
                  path: '**/node_modules'
                  key: dev-depends-bun${{ matrix.bun-version }}-${{ matrix.os }}-${{ hashFiles('bun.lockb') }}
            - name: Install dependencies
              if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
              run: bun i --frozen-lockfile
            - name: Cache Save devDependencies
              if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
              id: cache-save-dev-depends
              uses: actions/cache/save@v3
              with:
                  path: '**/node_modules'
                  key: dev-depends-bun${{ matrix.bun-version }}-${{ matrix.os }}-${{ hashFiles('bun.lockb') }}
    lint:
        needs: setup
        name: JavaScript Lint
        runs-on: ${{ matrix.os }}
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}
        strategy:
            matrix:
                bun-version: [1.0.1]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v3
            - name: Use Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: ${{ matrix.bun-version }}
            - name: Cache Restore devDependencies
              id: cache-restore-dev-depends
              uses: actions/cache/restore@v3
              with:
                  path: '**/node_modules'
                  key: dev-depends-bun${{ matrix.bun-version }}-${{ matrix.os }}-${{ hashFiles('bun.lockb') }}
            - name: Lint with yarn
              run: bun run lint:nofix:turbo
    test:
        needs: setup
        name: JavaScript Test
        runs-on: ${{ matrix.os }}
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}
        strategy:
            matrix:
                bun-version: [1.0.1]
                os: [ubuntu-latest]
                shard: [1/2, 2/2]
        steps:
            - uses: actions/checkout@v3
            - name: Use Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: ${{ matrix.bun-version }}
            - name: Cache Restore devDependencies
              id: cache-restore-dev-depends
              uses: actions/cache/restore@v3
              with:
                  path: '**/node_modules'
                  key: dev-depends-bun${{ matrix.bun-version }}-${{ matrix.os }}-${{ hashFiles('bun.lockb') }}
            - name: Run tests with bun
              run: bun run test:turbo -- -- --shard ${{ matrix.shard }} && bun run playwright test
    build:
        needs: [test, lint]
        name: JavaScript Build
        runs-on: ${{ matrix.os }}
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}
            MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
            NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        strategy:
            matrix:
                bun-version: [1.0.1]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v3
            - name: Use Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: ${{ matrix.bun-version }}
            - name: Cache Restore devDependencies
              id: cache-restore-dev-depends
              uses: actions/cache/restore@v3
              with:
                  path: '**/node_modules'
                  key: dev-depends-bun${{ matrix.bun-version }}-${{ matrix.os }}-${{ hashFiles('bun.lockb') }}
            - name: Build with bun
              run: bun run build:next:turbo